# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BestFilmForYou' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Swinject'
 # pod 'Alamofire'
 # pod 'Viperit'
  pod 'SDWebImage'
  
  target 'BestFilmForYouTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
